export class CreateAyt{
   matematikDogru:number=0;
   matematikYanlis:number=0;
   fizikDogru:number=0;
   fizikYanlis:number=0;
   kimyaDogru:number=0;
   kimyaYanlis:number=0;
   biyolojiDogru:number=0;
   biyolojiYanlis:number=0;
   edebiyatDogru:number=0;
   edebiyatYanlis:number=0;
   cografya1Dogru:number=0;
   cografya1Yanlis:number=0;
   tarih1Dogru:number=0;
   tarih1Yanlis:number=0;
   cografya2Dogru:number=0;
   cografya2Yanlis:number=0;
   tarih2Dogru:number=0;
   tarih2Yanlis:number=0;
   dinDogru:number=0;
   dinYanlis:number=0;
   felsefeDogru:number=0;
   felsefeYanlis:number=0;
   dilDogru:number=0;
   dilYanlis:number=0;
   yanlisKonularId:Array<string>=[];
   bosKonularId:Array<string>=[];
}